### ISSUE TITLE
Unable to install sense-hat with Bullseye OS

### ISSUE THREAD

**Issue by Mudary** [raspberrypi/rpi-sense#12]
Just wondering if there will be any support to use my sense-hat with Bullseye OS or is it limited to Bionic and below.

**Comment by pelwell** [comment]
Your issue title reads like a bug report, but there is no detail of what you have done and what the outcome was. Have another go.

**Comment by Mudary** [comment]
Topic should read 'Install sense-hat workaround for Bullseye OS' or something similar.
Thank you Pelwell, 
I used this workaround, since sense-hat is not on the Bullseye repo. (sudo) was added since I was not logged on as root.

https://forums.raspberrypi.com/viewtopic.php?t=280081
[Re: Can't Install SenseHat Support Software on Ubuntu](https://forums.raspberrypi.com/viewtopic.php?t=280081#p1759422)

[Thu Nov 12, 2020 1:34 pm](https://forums.raspberrypi.com/viewtopic.php?p=1759422&sid=22b82e6db0a10c80919dd9cb216df790#p1759422)
Hey, as far as RTIMU is concerned, download [this](https://github.com/RPi-Distro/RTIMULib/archive/b949681af69b45f0f7f4bb53b6770037b5b02178.zip) file first and extract to your home directory.

Once extracted, in terminal type:

Code: [Select all](https://forums.raspberrypi.com/viewtopic.php?t=280081#)

cd RTIMULib-master/Linux/python/
(sudo) python3 setup.py build
(sudo)python3 setup.py install

You may need to do the following if it is not installed already:

Code: [Select all](https://forums.raspberrypi.com/viewtopic.php?t=280081#)

sudo apt-get install python3-dev

You will also need to add your user to the input group:

Code: [Select all](https://forums.raspberrypi.com/viewtopic.php?t=280081#)

sudo addgroup USER_NAME input

You will now be able to access the sense hat using python.

Hope this helps

Allen

**Comment by pelwell** [comment]
As that thread says, if you have a problem with an Ubuntu OS you should report it to Canonical. _Our_ Bullseye RPiOS should work fine with the Sense HAT.

**Comment by mistotebe** [comment]
> As that thread says, if you have a problem with an Ubuntu OS you should report it to Canonical. _Our_ Bullseye RPiOS should work fine with the Sense HAT.

I am using (well, upgrading to) Raspbian: `deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi` and contrary to what you just said, `python3-sense-hat` has been removed from the distro.

**Comment by popcornmix** [comment]
```
$ sudo apt policy python3-sense-hat
python3-sense-hat:
  Installed: 2.2.0-2
  Candidate: 2.2.0-2
  Version table:
 *** 2.2.0-2 500
        500 http://archive.raspberrypi.org/debian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
```
It's in the raspberrypi repo, not raspbian. In RPiOS that is included from /etc/apt/sources.list.d/raspi.list
