### ISSUE TITLE
Minecraft window broken

### ISSUE THREAD

**Issue by bennuttall** [raspberrypi/rpi-sense#4]
I've noticed that since installing the new `sense-hat` package, the Minecraft window is messed up.

Steps to reproduce:

1. Open Minecraft Pi
1. Start game, Create new or enter existing world
1. Watch Minecraft window, move it around, try walking around
1. Notice Minecraft window randomly flicker black for periods of time
1. Maximise the Minecraft window and walk around, you'll see the Minecraft world flickering between the main display and what looks like a second display adjacent to the main one, in the overscan area.

Without the `sense-hat` package installed, the Minecraft window remains functional.

I imagine this is due to the Sense HAT and Minecraft Pi both writing to framebuffers.

This appears to be a new bug, as I successfully used Minecraft and the Sense HAT together back in May.

**Comment by XECDesign** [comment]
Can you confirm that it works as you expect with the latest raspberrypi-bootloader package but without the sense-hat package (after rebooting)? I can't think of any possible link between minecraft and the sense-hat package. I am wondering if it's possible that the kernel is the problem here.

**Comment by bennuttall** [comment]
I've uninstalled `sense-hat`, rebooted and still have the issue.

We tested it on Marc's Pi and I thought all we'd done is install `sense-hat`, but it turns out he also did an `apt-get upgrade`, so you're probably right.

I guess we close this issue and move it to the right place?

**Comment by XECDesign** [comment]
I don't think we know what the right place is yet. Leave it for now and I'll dig around later tonight.

**Comment by popcornmix** [comment]
I think you need to start with a clean raspbian install and identify if just 
``sudo apt-get update && sudo apt-get raspberrypi-bootloader``
causes the issue. That would show if firmware/kernel update causes the issue.

**Comment by XECDesign** [comment]
I am not able to reproduce this. Everything works as intended with overscan disabled. Enabling overscan shows minecraft being offset from its window. Maximising it has the offset glitch, but no flickering.

**Comment by bennuttall** [comment]
I think all we did was `apt-get update && apt-get upgrade`. I'm on leave now but ask @MarcScott - he has an SD card showing the bug.

**Comment by bennuttall** [comment]
https://twitter.com/Halfpintgill/status/640099820653420544

**Comment by bennuttall** [comment]
I've just reproduced this with a copy of the office admin SD card - the one in Nicola's drawer. Initially Minecraft works fine. After running `sudo apt-get install sense-hat` and rebooting, the error appears.

I can confirm the bug also appears when running `sudo apt-get install raspberrypi-bootloader` on a clean SD card.

I've left a card on Serge's desk with a note.

**Comment by XECDesign** [comment]
This is starting to be a widely reported issue on the forum as well.

I have tried the card and an indeed seeing the problem. There was a report online that adjusting the memory split worked for somebody, that that's not the case here. The gl context seems to be behind the X11 stuff. The only difference I can see between our setups is that this card uses NOOBS whereas mine had the raw image.

@popcornmix Have there been any changes to the framebuffer driver or the firmware which would mess with the z-levels of things? Is there any way this could have caused the problem? https://github.com/raspberrypi/linux/commit/a15106c0300ea7958fa7e1cc62c573d999eb4ee2

If it's not something that obvious, could I give you the card to take a look at with the debugger attached?

**Comment by XECDesign** [comment]
After a bit of testing, it's definitely a kernel-side problem. Bisecting to find the problem now.

**Comment by XECDesign** [comment]
Handing it over to the kernel folks
