### ISSUE TITLE
Atmel code inconsistent with PaspberryPi 4.1 kernel driver?

### ISSUE THREAD

**Issue by jburgess777** [raspberrypi/rpi-sense#5]
I notice that the framebuffer driver + firmware in this repository looks like it wants a 192 byte I2C transfer but the current code in the main kernel driver writes 193 bytes. 

The driver in this repo has:
```
driver/ledhatfb.c:    i2c_master_send(ledhat_dev.client, array, 192);
```
The current RaspberryPi linux-4.1 kernel source has:
```
drivers/video/fbdev/rpisense-fb.c:      rpisense_block_write(rpisense, vmem_work, 193);
```
I'd like to try tweaking current gain of the RGB channels to boost the brightness of the blue LEDs and this difference in the driver code makes me suspect that the Atmel code is out of date. Do you know if the firmware in this repo will be updated or can I get it elsewhere?

**Comment by XECDesign** [comment]
The driver in the repo is indeed early WIP version and should be removed. The atmel code is up to date though.

**Comment by jburgess777** [comment]
OK, I'll see if I can backup my current firmware and try out my own version. I saw that there was some existing code for accessing the control registers of the LED chip which I might be able to use but the fact that this seemed to be only half-implemented made me wonder if the current code was up to date.

**Comment by XECDesign** [comment]
Yeah, it was a little rushed. Got to a 'good enough' stage and had to move on. If would be willing to add the missing features, it would certainly be much appreciates.
