### ISSUE TITLE
Where in the kernel is the driver?

### ISSUE THREAD

**Issue by thealch3m1st** [raspberrypi/rpi-sense#7]
I'm trying to understand how the led matrix and joystick work because I'm trying to make a board that will behave similarly to the sense hat.

The commit message here (https://github.com/raspberrypi/rpi-sense/commit/6b0eb268d07864c4bda4615055098431f24b5144) says: "Remove driver (already included in the kernel)"

But I can't find it anywhere.

**Comment by XECDesign** [comment]
https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/mfd/rpisense-core.c
https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/input/joystick/rpisense-js.c
https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/video/fbdev/rpisense-fb.c

**Comment by thealch3m1st** [comment]
@XECDesign Thank you very much!
